/* autogenerated by Processing revision 1310 on 2025-11-23 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import fr.dgac.ivy.*;
import fr.dgac.ivy.tools.*;
import gnu.getopt.*;

import java.awt.Point;
import fr.dgac.ivy.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Palette extends PApplet {

/*
 * Palette Graphique - prélude au projet multimodal 3A SRI
 * 4 objets gérés : cercle, rectangle(carré), losange et triangle
 * (c) 05/11/2019
 * Dernière révision : 28/04/2020
 */
 



Ivy bus;


ArrayList<Forme> formes; // liste de formes stockées
FSM mae; // Finite Sate Machine
int indice_forme;
PImage sketch_icon;


public void setup() {
  /* size commented out by preprocessor */;
  surface.setResizable(true);
  surface.setTitle("Palette multimodale");
  surface.setLocation(20,20);
  sketch_icon = loadImage("Palette.jpg");
  surface.setIcon(sketch_icon);
  
  formes= new ArrayList();
  noStroke();
  mae = FSM.INITIAL;
  indice_forme = -1;
  try {
    bus = new Ivy("Palette", "Palette is ready", null);
    bus.start("127.0.0.1:2010");
      bus.bindMsg("FUSION: ACTION=(.*) WHERE=(.*) FORME=(.*) COULEUR=(.*) LOCALISATION=(.*) COORDONNES=(.*)", 
  new IvyMessageListener() {
    public void receive(IvyClient client, String[] args) {
      handleFusion(args[0], args[2], args[3], args[5]);
    }
});
  } catch (IvyException ie) {
    println("Erreur Ivy : " + ie.getMessage());
  }
}

public void draw() {
  background(0);
  //println("MAE : " + mae + " indice forme active ; " + indice_forme);
  switch (mae) {
    case INITIAL:  // Etat INITIAL
      background(255);
      fill(0);
      text("Etat initial (c(ercle)/l(osange)/r(ectangle)/t(riangle) pour créer la forme à la position courante)", 50,50);
      text("m(ove)+ click pour sélectionner un objet et click pour sa nouvelle position", 50,80);
      break;
      
    case AFFICHER_FORMES:  // 
    case DEPLACER_FORMES_SELECTION: 
    case DEPLACER_FORMES_DESTINATION: 
      affiche();
      break;   
      
    default:
      break;
  }  
}

// fonction d'affichage des formes m
public void affiche() {
  background(255);
  /* afficher tous les objets */
  for (int i=0;i<formes.size();i++) // on affiche les objets de la liste
    (formes.get(i)).update();
}

public void mousePressed() { // sur l'événement clic
  Point p = new Point(mouseX,mouseY);
  String c = "undefined";
  
  switch (mae) {
    case AFFICHER_FORMES:
      for (Forme f : formes) {
        if (f.isClicked(p)) {

          c =  nameFromColor(f.getColor());
          println(">>> CLICKED FORME = " + f.getClass().getSimpleName()
                  + " color = " + c);
          break;
        }
      }
      break;
      
   case DEPLACER_FORMES_SELECTION:
     for (int i=0;i<formes.size();i++) { // we're trying every object in the list        
        if ((formes.get(i)).isClicked(p)) {
          indice_forme = i;
          mae = FSM.DEPLACER_FORMES_DESTINATION;
        }         
     }
     if (indice_forme == -1)
       mae= FSM.AFFICHER_FORMES;
     break;
     
   case DEPLACER_FORMES_DESTINATION:
     if (indice_forme !=-1)
       (formes.get(indice_forme)).setLocation(new Point(mouseX,mouseY));
     indice_forme=-1;
     mae=FSM.AFFICHER_FORMES;
     break;
     
    default:
      break;
  }
  if (bus != null) {
    try {
      bus.sendMsg("Palette Click couleur=" + c + " x=" + mouseX + " y=" + mouseY);
    } catch (IvyException ie) {
      println("Erreur envoi Ivy : " + ie.getMessage());
    }
  }
}


public void keyPressed() {
  Point p = new Point(mouseX,mouseY);
  switch(key) {
    case 'r':
      Forme f= new Rectangle(p);
      formes.add(f);
      mae=FSM.AFFICHER_FORMES;
      break;
      
    case 'c':
      Forme f2=new Cercle(p);
      formes.add(f2);
      mae=FSM.AFFICHER_FORMES;
      break;
    
    case 't':
      Forme f3=new Triangle(p);
      formes.add(f3);
       mae=FSM.AFFICHER_FORMES;
      break;  
      
    case 'l':
      Forme f4=new Losange(p);
      formes.add(f4);
      mae=FSM.AFFICHER_FORMES;
      break;
      
      case 'a':
      Forme f5=new Carre(p);
      formes.add(f5);
      mae=FSM.AFFICHER_FORMES;
      break;
      
      
    case 'm' : // move
      mae=FSM.DEPLACER_FORMES_SELECTION;
      break;
  }
}

public void handleFusion(String action, String forme, String couleur, String coordString) {

  ArrayList<Point> coords = new ArrayList<Point>();

try {
    // Remove all brackets
    coordString = coordString.replace("[", "").replace("]", "");

    // Now split into coordinate pairs: "607, 359, 611, 275"
    String[] nums = coordString.split(",");

    // Should always be even: x1,y1,x2,y2,...
    for (int i = 0; i + 1 < nums.length; i += 2) {
        int x = PApplet.parseInt(nums[i].trim());
        int y = PApplet.parseInt(nums[i+1].trim());
        coords.add(new Point(x, y));
        println(">>> coords = " + x + "," + y);
    }

} catch(Exception e) {
    println("Error parsing coords: " + coordString);
}

  println(">>> FUSION RECUE action=" + action + " forme=" + forme + " couleur=" + couleur + " coords=" + coords);

  // ---------------------------------------------------------------------
  // 1) CREATE
  // ---------------------------------------------------------------------
  if (action.equalsIgnoreCase("CREATE")) {

    if (coords.size() < 1) return;

    Point p = coords.get(0);
    Forme f = null;

    switch(forme.toUpperCase()) {
      case "CERCLE":  f = new Cercle(p);  break;
      case "RECTANGLE": f = new Rectangle(p); break;
      case "TRIANGLE": f = new Triangle(p); break;
      case "CARRE": f = new Carre(p); break;
      case "LOSANGE":  f = new Losange(p); break;
    }

    if (f != null) {
      if (!couleur.equals("") && !couleur.equals("undefined"))
        f.setColor(colorFromName(couleur));
      formes.add(f);
      mae = FSM.AFFICHER_FORMES;
    }
  }

// ---------------------------------------------------------------------
// 2) DELETE
// ---------------------------------------------------------------------
else if (action.equalsIgnoreCase("DELETE")) {

  Forme target = null;

  // ------------------------------------------------------------
  // A) DELETE coords
  // ------------------------------------------------------------
  if (coords.size() > 0) {
    Point p = coords.get(0);
    for (Forme f : formes) {
      if (f.isClicked(p)) {
        target = f;
        break;
      }
    }
  }

  // ------------------------------------------------------------
  // B) DELETE couleur + forme (seulement si non AMBIGU)
  // ------------------------------------------------------------
  else if (!forme.equals("undefined")&& !couleur.equals("undefined")) {
    

    ArrayList<Forme> matches = new ArrayList<Forme>();

    for (Forme f : formes) {
      println(f);
      // compare la forme et la couleur
      if (f.getClass().getSimpleName().equalsIgnoreCase(forme)
          && approxColor(f.getColor(), colorFromName(couleur))) {
        matches.add(f);
      }
    }
    println(matches.size());

    if (matches.size() > 1) {
      println(">>> DELETE ABANDON — ambigu (" + matches.size() + " correspondances)");
      return;
    }
      if (matches.size() == 1){
      target = matches.get(0);
    }
  }

  
  else if (!forme.equals("undefined")){
    

    ArrayList<Forme> matches = new ArrayList<Forme>();

    for (Forme f : formes) {
      println(f);
      // compare la forme
      if (f.getClass().getSimpleName().equalsIgnoreCase(forme)) {
        matches.add(f);
      }
    }
    println(matches.size());

    if (matches.size() > 1) {
        println(">>> DELETE ABANDON — ambigu (" + matches.size() + " correspondances)");
      return;
    }

    if (matches.size() == 1){
      target = matches.get(0);
    }
  }

  else if (!couleur.equals("undefined")){
    
    

    ArrayList<Forme> matches = new ArrayList<Forme>();

    for (Forme f : formes) {
      println(f);
      // compare la couleur
      if (approxColor(f.getColor(), colorFromName(couleur))) {
        matches.add(f);
      }
    }
    println(matches.size());

    if (matches.size() > 1) {
        println(">>> DELETE ABANDON — ambigu (" + matches.size() + " correspondances)");
      return;
    }

    if (matches.size() == 1){
      target = matches.get(0);
    }
  }

  // ------------------------------------------------------------
  // Final deletion
  // ------------------------------------------------------------
  if (target != null) {
    formes.remove(target);
    mae = FSM.AFFICHER_FORMES;
  }
}

  // ---------------------------------------------------------------------
  // 3) MOVE 
  // ---------------------------------------------------------------------
  else if (action.equalsIgnoreCase("MOVE")) {
    Forme target = null;
    
  // ---------------------------------------------------------------------
  // A) MOVE : coord 1 → coord 2
  // ---------------------------------------------------------------------
    if (coords.size() > 2){

      Point source = coords.get(0);
      Point dest = coords.get(1);
  
      for (Forme f : formes) {
        if (f.isClicked(source)) {
          f.setLocation(dest);
          mae = FSM.AFFICHER_FORMES;
          break;
        }
      }
    }
  // ------------------------------------------------------------
  // B) MOVE forme (seulement si non AMBIGU)
  // ------------------------------------------------------------
    else if (coords.size()==1 && !forme.equals("undefined")){
       ArrayList<Forme> matches = new ArrayList<Forme>();
       
      for (Forme f : formes) {
        println(f);
        // compare la forme et la couleur
        if (f.getClass().getSimpleName().equalsIgnoreCase(forme)) {
          matches.add(f);
        }
      }
      println(matches.size());
  
      if (matches.size() > 1) {
        println(">>> MOVE ABANDON — ambigu (" + matches.size() + " correspondances)");
        return;
      }
        if (matches.size() == 1){
          target = matches.get(0);
      }
       
    }
    // ------------------------------------------------------------
    // C) MOVE couleur (seulement si non AMBIGU)
    // ------------------------------------------------------------
    else if (coords.size()==1 && !couleur.equals("undefined")){
       ArrayList<Forme> matches = new ArrayList<Forme>();
      
      for (Forme f : formes) {
        println(f);
        // compare la forme et la couleur
        if (approxColor(f.getColor(), colorFromName(couleur))) {
          matches.add(f);
        }
      }
      println(matches.size());
  
      if (matches.size() > 1) {
        println(">>> MOVE ABANDON — ambigu (" + matches.size() + " correspondances)");
        return;
      }
        if (matches.size() == 1){
          target = matches.get(0);
      }
    }
    // ------------------------------------------------------------
    // D) MOVE forme et couleur (seulement si non AMBIGU)
    // ------------------------------------------------------------
    else if (coords.size()==1 && !forme.equals("undefined") && !couleur.equals("undefined")){
       ArrayList<Forme> matches = new ArrayList<Forme>();
       
      for (Forme f : formes) {
        println(f);
        // compare la forme et la couleur
        if (f.getClass().getSimpleName().equalsIgnoreCase(forme)
            && approxColor(f.getColor(), colorFromName(couleur))) {
          matches.add(f);
        }
      }
      println(matches.size());
  
      if (matches.size() > 1) {
        println(">>> DELETE ABANDON — ambigu (" + matches.size() + " correspondances)");
        return;
      }
        if (matches.size() == 1){
          target = matches.get(0);
      }
    }
    if (target!=null){
      target.setLocation(coords.get(0));
      mae = FSM.AFFICHER_FORMES;
    }
    
  }
}


public int colorFromName(String name) {
  if (name == null) return color(200);

  switch(name.toUpperCase()) {
    case "RED":
      return color(255, 0, 0);

    case "ORANGE":
      return color(255, 128, 0);

    case "YELLOW":
      return color(255, 255, 0);

    case "GREEN":
      return color(0, 255, 0);

    case "BLUE":
      return color(0, 0, 255);

    case "PURPLE":
      return color(160, 32, 240);  // vivid purple

    case "DARK":
      return color(30, 30, 30);    // nearly black
  }

  // default neutral gray
  return color(200, 200, 200);
}


public boolean approxColor(int c1, int c2) {
  return abs(red(c1)-red(c2)) < 40 &&
         abs(green(c1)-green(c2)) < 40 &&
         abs(blue(c1)-blue(c2)) < 40;
}

public String nameFromColor(int c) {
  if (c == color(255, 0, 0))     return "RED";
  if (c == color(255,128, 0))    return "ORANGE";
  if (c == color(255,255, 0))    return "YELLOW";
  if (c == color(0, 255, 0))     return "GREEN";
  if (c == color(0, 0, 255))     return "BLUE";
  if (c == color(160,32,240))    return "PURPLE";
  if (c == color(30,30,30))      return "DARK";
  if (c == color(200,200,200))   return "GRAY";

  return "UNKNOWN";
}
/*
 * Classe Rectangle
 */ 
 
public class Carre extends Forme {
  
  int longueur;
  
  public Carre(Point p) {
    super(p);
    this.longueur=60;
  }
   
  public void update() {
    fill(this.c);
    square((int) this.origin.getX(),(int) this.origin.getY(),this.longueur);
  }  
  
  public boolean isClicked(Point p) {
    int x= (int) p.getX();
    int y= (int) p.getY();
    int x0 = (int) this.origin.getX();
    int y0 = (int) this.origin.getY();
    
    // vérifier que le rectangle est cliqué
    if ((x>x0) && (x<x0+this.longueur) && (y>y0) && (y<y0+this.longueur))
      return(true);
    else  
      return(false);
  }
  
  // Calcul du périmètre du carré
  protected double perimetre() {
    return(this.longueur*4);
  }
  
  protected double aire(){
    return(this.longueur*this.longueur);
  }
}
/*
 * Classe Cercle
 */ 
 
public class Cercle extends Forme {
  
  int rayon;
  
  public Cercle(Point p) {
    super(p);
    this.rayon=80;
  }
   
  public void update() {
    fill(this.c);
    circle((int) this.origin.getX(),(int) this.origin.getY(),this.rayon);
  }  
   
  public boolean isClicked(Point p) {
    // vérifier que le cercle est cliqué
   PVector OM= new PVector( (int) (p.getX() - this.origin.getX()),(int) (p.getY() - this.origin.getY())); 
   if (OM.mag() <= this.rayon/2)
     return(true);
   else 
     return(false);
  }
  
  protected double perimetre() {
    return(2*PI*this.rayon);
  }
  
  protected double aire(){
    return(PI*this.rayon*this.rayon);
  }
}
/*
 * Enumération de a Machine à Etats (Finite State Machine)
 *
 *
 */
 
public enum FSM {
  INITIAL, /* Etat Initial */ 
  AFFICHER_FORMES, 
  DEPLACER_FORMES_SELECTION,
  DEPLACER_FORMES_DESTINATION
}
/*****
 * Création d'un nouvelle classe objet : Forme (Cercle, Rectangle, Triangle
 * 
 * Date dernière modification : 28/10/2019
 */

abstract class Forme {
 Point origin;
 int c;
 
 Forme(Point p) {
   this.origin=p;
   this.c = color(127);
 }
 
 public void setColor(int c) {
   this.c=c;
 }
 
 public int getColor(){
   return(this.c);
 }
 
 public abstract void update();
 
 public Point getLocation() {
   return(this.origin);
 }
 
 public void setLocation(Point p) {
   this.origin = p;
 }
 
 public abstract boolean isClicked(Point p);
 
 // Calcul de la distance entre 2 points
 protected double distance(Point A, Point B) {
    PVector AB = new PVector( (int) (B.getX() - A.getX()),(int) (B.getY() - A.getY())); 
    return(AB.mag());
 }
 
 protected abstract double perimetre();
 protected abstract double aire();
}
/*
 * Classe Losange
 */ 
 
public class Losange extends Forme {
  Point A, B,C,D;
  
  public Losange(Point p) {
    super(p);
    // placement des points
    A = new Point();    
    A.setLocation(p);
    B = new Point();    
    B.setLocation(A);
    C = new Point();  
    C.setLocation(A);
    D = new Point();
    D.setLocation(A);
    B.translate(40,60);
    D.translate(-40,60);
    C.translate(0,120);
  }
  
  public void setLocation(Point p) {
      super.setLocation(p);
      // redéfinition de l'emplacement des points
      A.setLocation(p);   
      B.setLocation(A);  
      C.setLocation(A);
      D.setLocation(A);
      B.translate(40,60);
      D.translate(-40,60);
      C.translate(0,120);   
  }
  
  public void update() {
    fill(this.c);
    quad((float) A.getX(), (float) A.getY(), (float) B.getX(), (float) B.getY(), (float) C.getX(), (float) C.getY(),  (float) D.getX(),  (float) D.getY());
  }  
  
  public boolean isClicked(Point M) {
    // vérifier que le losange est cliqué
    // aire du rectangle AMD + AMB + BMC + CMD = aire losange  
    if (round( (float) (aire_triangle(A,M,D) + aire_triangle(A,M,B) + aire_triangle(B,M,C) + aire_triangle(C,M,D))) == round((float) aire()))
      return(true);
    else 
      return(false);  
  }
  
  protected double perimetre() {
    //
    PVector AB= new PVector( (int) (B.getX() - A.getX()),(int) (B.getY() - A.getY())); 
    PVector BC= new PVector( (int) (C.getX() - B.getX()),(int) (C.getY() - B.getY())); 
    PVector CD= new PVector( (int) (D.getX() - C.getX()),(int) (D.getY() - C.getY())); 
    PVector DA= new PVector( (int) (A.getX() - D.getX()),(int) (A.getY() - D.getY())); 
    return( AB.mag()+BC.mag()+CD.mag()+DA.mag()); 
  }
  
  protected double aire(){
    PVector AC= new PVector( (int) (C.getX() - A.getX()),(int) (C.getY() - A.getY())); 
    PVector BD= new PVector( (int) (D.getX() - B.getX()),(int) (D.getY() - B.getY())); 
    return((AC.mag()*BD.mag())/2);
  } 
  
  private double perimetre_triangle(Point I, Point J, Point K) {
    //
    PVector IJ= new PVector( (int) (J.getX() - I.getX()),(int) (J.getY() - I.getY())); 
    PVector JK= new PVector( (int) (K.getX() - J.getX()),(int) (K.getY() - J.getY())); 
    PVector KI= new PVector( (int) (I.getX() - K.getX()),(int) (I.getY() - K.getY())); 
    
    return( IJ.mag()+JK.mag()+KI.mag()); 
  }
   
  // Calcul de l'aire d'un triangle par la méthode de Héron 
  private double aire_triangle(Point I, Point J, Point K){
    double s = perimetre_triangle(I,J,K)/2;
    double aire = s*(s-distance(I,J))*(s-distance(J,K))*(s-distance(K,I));
    return(sqrt((float) aire));
  }
}
/*
 * Classe Rectangle
 */ 
 
public class Rectangle extends Forme {
  
  int longueur;
  int largeur;
  
  public Rectangle(Point p) {
    super(p);
    this.longueur=60;
    this.largeur=30;
  }
   
  public void update() {
    fill(this.c);
    rect((int) this.origin.getX(),(int) this.origin.getY(),this.longueur, this.largeur);
  }  
  
  public boolean isClicked(Point p) {
    int x= (int) p.getX();
    int y= (int) p.getY();
    int x0 = (int) this.origin.getX();
    int y0 = (int) this.origin.getY();
    
    // vérifier que le rectangle est cliqué
    if ((x>x0) && (x<x0+this.longueur) && (y>y0) && (y<y0+this.longueur))
      return(true);
    else  
      return(false);
  }
  
  // Calcul du périmètre du carré
  protected double perimetre() {
    return(this.longueur*this.largeur);
  }
  
  protected double aire(){
    return(this.longueur*this.longueur);
  }
}
/*
 * Classe Triangle
 */ 
 
public class Triangle extends Forme {
  Point A, B,C;
  public Triangle(Point p) {
    super(p);
    // placement des points
    A = new Point();    
    A.setLocation(p);
    B = new Point();    
    B.setLocation(A);
    C = new Point();    
    C.setLocation(A);
    B.translate(40,60);
    C.translate(-40,60);
  }
  
    public void setLocation(Point p) {
      super.setLocation(p);
      // redéfinition de l'emplacement des points
      A.setLocation(p);   
      B.setLocation(A);  
      C.setLocation(A);
      B.translate(40,60);
      C.translate(-40,60);   
  }
  
  public void update() {
    fill(this.c);
    triangle((float) A.getX(), (float) A.getY(), (float) B.getX(), (float) B.getY(), (float) C.getX(), (float) C.getY());
  }  
  
  public boolean isClicked(Point M) {
    // vérifier que le triangle est cliqué
    
    PVector AB= new PVector( (int) (B.getX() - A.getX()),(int) (B.getY() - A.getY())); 
    PVector AC= new PVector( (int) (C.getX() - A.getX()),(int) (C.getY() - A.getY())); 
    PVector AM= new PVector( (int) (M.getX() - A.getX()),(int) (M.getY() - A.getY())); 
    
    PVector BA= new PVector( (int) (A.getX() - B.getX()),(int) (A.getY() - B.getY())); 
    PVector BC= new PVector( (int) (C.getX() - B.getX()),(int) (C.getY() - B.getY())); 
    PVector BM= new PVector( (int) (M.getX() - B.getX()),(int) (M.getY() - B.getY())); 
    
    PVector CA= new PVector( (int) (A.getX() - C.getX()),(int) (A.getY() - C.getY())); 
    PVector CB= new PVector( (int) (B.getX() - C.getX()),(int) (B.getY() - C.getY())); 
    PVector CM= new PVector( (int) (M.getX() - C.getX()),(int) (M.getY() - C.getY())); 
    
    if ( ((AB.cross(AM)).dot(AM.cross(AC)) >=0) && ((BA.cross(BM)).dot(BM.cross(BC)) >=0) && ((CA.cross(CM)).dot(CM.cross(CB)) >=0) ) { 
      return(true);
    }
    else
      return(false);
  }
  
  protected double perimetre() {
    //
    PVector AB= new PVector( (int) (B.getX() - A.getX()),(int) (B.getY() - A.getY())); 
    PVector AC= new PVector( (int) (C.getX() - A.getX()),(int) (C.getY() - A.getY())); 
    PVector BC= new PVector( (int) (C.getX() - B.getX()),(int) (C.getY() - B.getY())); 
    
    return( AB.mag()+AC.mag()+BC.mag()); 
  }
   
  // Calcul de l'aire du triangle par la méthode de Héron 
  protected double aire(){
    double s = perimetre()/2;
    double aire = s*(s-distance(B,C))*(s-distance(A,C))*(s-distance(A,B));
    return(sqrt((float) aire));
  }
}


  public void settings() { size(800, 600); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Palette" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
